/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package btllib;

public class _Data {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _Data(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_Data obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        btllibJNI.delete__Data(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public _Data(SWIGTYPE_p_FILE file, SWIGTYPE_p_pid_t pid) {
    this(btllibJNI.new__Data(SWIGTYPE_p_FILE.getCPtr(file), SWIGTYPE_p_pid_t.getCPtr(pid)), true);
  }

  public SWIGTYPE_p_FILE __ref__() {
    long cPtr = btllibJNI._Data___ref__(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_FILE(cPtr, false);
  }

  public SWIGTYPE_p_FILE __deref__() {
    long cPtr = btllibJNI._Data___deref__(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_FILE(cPtr, false);
  }

  public void setFile(SWIGTYPE_p_FILE value) {
    btllibJNI._Data_file_set(swigCPtr, this, SWIGTYPE_p_FILE.getCPtr(value));
  }

  public SWIGTYPE_p_FILE getFile() {
    long cPtr = btllibJNI._Data_file_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_FILE(cPtr, false);
  }

  public void setPid(SWIGTYPE_p_pid_t value) {
    btllibJNI._Data_pid_set(swigCPtr, this, SWIGTYPE_p_pid_t.getCPtr(value));
  }

  public SWIGTYPE_p_pid_t getPid() {
    return new SWIGTYPE_p_pid_t(btllibJNI._Data_pid_get(swigCPtr, this), true);
  }

  public void setClosed(boolean value) {
    btllibJNI._Data_closed_set(swigCPtr, this, value);
  }

  public boolean getClosed() {
    return btllibJNI._Data_closed_get(swigCPtr, this);
  }

}
