/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package btllib;

public class _Pipeline {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _Pipeline(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_Pipeline obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        btllibJNI.delete__Pipeline(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public _Pipeline() {
    this(btllibJNI.new__Pipeline__SWIG_0(), true);
  }

  public _Pipeline(int fd, SWIGTYPE_p_pid_t pid_first, SWIGTYPE_p_pid_t pid_last) {
    this(btllibJNI.new__Pipeline__SWIG_1(fd, SWIGTYPE_p_pid_t.getCPtr(pid_first), SWIGTYPE_p_pid_t.getCPtr(pid_last)), true);
  }

  public void setFd(int value) {
    btllibJNI._Pipeline_fd_set(swigCPtr, this, value);
  }

  public int getFd() {
    return btllibJNI._Pipeline_fd_get(swigCPtr, this);
  }

  public void setPid_first(SWIGTYPE_p_pid_t value) {
    btllibJNI._Pipeline_pid_first_set(swigCPtr, this, SWIGTYPE_p_pid_t.getCPtr(value));
  }

  public SWIGTYPE_p_pid_t getPid_first() {
    return new SWIGTYPE_p_pid_t(btllibJNI._Pipeline_pid_first_get(swigCPtr, this), true);
  }

  public void setPid_last(SWIGTYPE_p_pid_t value) {
    btllibJNI._Pipeline_pid_last_set(swigCPtr, this, SWIGTYPE_p_pid_t.getCPtr(value));
  }

  public SWIGTYPE_p_pid_t getPid_last() {
    return new SWIGTYPE_p_pid_t(btllibJNI._Pipeline_pid_last_get(swigCPtr, this), true);
  }

}
