/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Base {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Base(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Base obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        btlJNI.delete_Base(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Base(Base base) {
    this(btlJNI.new_Base(Base.getCPtr(base), base), true);
  }

  public void complement() {
    btlJNI.Base_complement(swigCPtr, this);
  }

  public char getComplement() {
    return btlJNI.Base_getComplement(swigCPtr, this);
  }

  public void validate() {
    btlJNI.Base_validate__SWIG_0(swigCPtr, this);
  }

  public void capitalize() {
    btlJNI.Base_capitalize__SWIG_0(swigCPtr, this);
  }

  public static void validate(char base) {
    btlJNI.Base_validate__SWIG_1(base);
  }

  public static char capitalize(char base) {
    return btlJNI.Base_capitalize__SWIG_1(base);
  }

}
