/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class btl {
  public static String get_time() {
    return btlJNI.get_time();
  }

  public static void log_info(String msg) {
    btlJNI.log_info(msg);
  }

  public static void log_warning(String msg) {
    btlJNI.log_warning(msg);
  }

  public static void log_error(String msg) {
    btlJNI.log_error(msg);
  }

  public static void check_error(boolean condition, String msg) {
    btlJNI.check_error(condition, msg);
  }

  public static void check_warning(boolean condition, String msg) {
    btlJNI.check_warning(condition, msg);
  }

  public static void check_stream(SWIGTYPE_p_std__ios stream, String name) {
    btlJNI.check_stream(SWIGTYPE_p_std__ios.getCPtr(stream), name);
  }

  public static String getCOMPLEMENTS() {
    return btlJNI.COMPLEMENTS_get();
  }

  public static String getCAPITALS() {
    return btlJNI.CAPITALS_get();
  }

}
