/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package btllib;

public interface btllibConstants {
  public final static int BTLLIB_NTHASH_ITERATOR_H = btllibJNI.BTLLIB_NTHASH_ITERATOR_H_get();
}
