/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class btllib {
  public static SWIGTYPE_p_std__vectorT_std__string_t split(String s, String delim) {
    return new SWIGTYPE_p_std__vectorT_std__string_t(btllibJNI.split(s, delim), true);
  }

  public static void ltrim(SWIGTYPE_p_std__string s) {
    btllibJNI.ltrim(SWIGTYPE_p_std__string.getCPtr(s));
  }

  public static void rtrim(SWIGTYPE_p_std__string s) {
    btllibJNI.rtrim(SWIGTYPE_p_std__string.getCPtr(s));
  }

  public static void trim(SWIGTYPE_p_std__string s) {
    btllibJNI.trim(SWIGTYPE_p_std__string.getCPtr(s));
  }

  public static boolean starts_with(String s, String prefix) {
    return btllibJNI.starts_with(s, prefix);
  }

  public static boolean ends_with(String s, String suffix) {
    return btllibJNI.ends_with(s, suffix);
  }

  public static void setOrig_open(SWIGTYPE_p_f_p_q_const__char_int_mode_t__int value) {
    btllibJNI.orig_open_set(SWIGTYPE_p_f_p_q_const__char_int_mode_t__int.getCPtr(value));
  }

  public static SWIGTYPE_p_f_p_q_const__char_int_mode_t__int getOrig_open() {
    long cPtr = btllibJNI.orig_open_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__char_int_mode_t__int(cPtr, false);
  }

  public static void setOrig_open64(SWIGTYPE_p_f_p_q_const__char_int_mode_t__int value) {
    btllibJNI.orig_open64_set(SWIGTYPE_p_f_p_q_const__char_int_mode_t__int.getCPtr(value));
  }

  public static SWIGTYPE_p_f_p_q_const__char_int_mode_t__int getOrig_open64() {
    long cPtr = btllibJNI.orig_open64_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__char_int_mode_t__int(cPtr, false);
  }

  public static void setOrig_creat(SWIGTYPE_p_f_p_q_const__char_mode_t__int value) {
    btllibJNI.orig_creat_set(SWIGTYPE_p_f_p_q_const__char_mode_t__int.getCPtr(value));
  }

  public static SWIGTYPE_p_f_p_q_const__char_mode_t__int getOrig_creat() {
    long cPtr = btllibJNI.orig_creat_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__char_mode_t__int(cPtr, false);
  }

  public static void setOrig_fopen(SWIGTYPE_p_f_p_q_const__char_p_q_const__char__p_FILE value) {
    btllibJNI.orig_fopen_set(SWIGTYPE_p_f_p_q_const__char_p_q_const__char__p_FILE.getCPtr(value));
  }

  public static SWIGTYPE_p_f_p_q_const__char_p_q_const__char__p_FILE getOrig_fopen() {
    long cPtr = btllibJNI.orig_fopen_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__char_p_q_const__char__p_FILE(cPtr, false);
  }

  public static void setOrig_fopen64(SWIGTYPE_p_f_p_q_const__char_p_q_const__char__p_FILE value) {
    btllibJNI.orig_fopen64_set(SWIGTYPE_p_f_p_q_const__char_p_q_const__char__p_FILE.getCPtr(value));
  }

  public static SWIGTYPE_p_f_p_q_const__char_p_q_const__char__p_FILE getOrig_fopen64() {
    long cPtr = btllibJNI.orig_fopen64_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__char_p_q_const__char__p_FILE(cPtr, false);
  }

  public static void sigchld_handler(int sig) {
    btllibJNI.sigchld_handler(sig);
  }

  public static boolean data_saveload_init() {
    return btllibJNI.data_saveload_init();
  }

  public static boolean getData_saveload_initialized() {
    return btllibJNI.data_saveload_initialized_get();
  }

  public static String get_saveload_cmd(String path, boolean save) {
    return btllibJNI.get_saveload_cmd(path, save);
  }

  public static int data_saveload(String cmd, boolean save) {
    return btllibJNI.data_saveload(cmd, save);
  }

  public static SWIGTYPE_p_FILE fdata_saveload(String cmd, boolean save) {
    long cPtr = btllibJNI.fdata_saveload(cmd, save);
    return (cPtr == 0) ? null : new SWIGTYPE_p_FILE(cPtr, false);
  }

  public static int open(String pathname, int flags, SWIGTYPE_p_mode_t mode) {
    return btllibJNI.open(pathname, flags, SWIGTYPE_p_mode_t.getCPtr(mode));
  }

  public static int open64(String pathname, int flags, SWIGTYPE_p_mode_t mode) {
    return btllibJNI.open64(pathname, flags, SWIGTYPE_p_mode_t.getCPtr(mode));
  }

  public static int creat(String pathname, SWIGTYPE_p_mode_t mode) {
    return btllibJNI.creat(pathname, SWIGTYPE_p_mode_t.getCPtr(mode));
  }

  public static SWIGTYPE_p_FILE fopen(String pathname, String mode) {
    long cPtr = btllibJNI.fopen(pathname, mode);
    return (cPtr == 0) ? null : new SWIGTYPE_p_FILE(cPtr, false);
  }

  public static SWIGTYPE_p_FILE fopen64(String pathname, String mode) {
    long cPtr = btllibJNI.fopen64(pathname, mode);
    return (cPtr == 0) ? null : new SWIGTYPE_p_FILE(cPtr, false);
  }

  public static String get_time() {
    return btllibJNI.get_time();
  }

  public static void log_info(String msg) {
    btllibJNI.log_info(msg);
  }

  public static void log_warning(String msg) {
    btllibJNI.log_warning(msg);
  }

  public static void log_error(String msg) {
    btllibJNI.log_error(msg);
  }

  public static void check_error(boolean condition, String msg) {
    btllibJNI.check_error(condition, msg);
  }

  public static void check_warning(boolean condition, String msg) {
    btllibJNI.check_warning(condition, msg);
  }

  public static void check_stream(SWIGTYPE_p_std__ios stream, String name) {
    btllibJNI.check_stream(SWIGTYPE_p_std__ios.getCPtr(stream), name);
  }

  public static String getCOMPLEMENTS() {
    return btllibJNI.COMPLEMENTS_get();
  }

  public static String getCAPITALS() {
    return btllibJNI.CAPITALS_get();
  }

}
