/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class btllibJNI {
  public final static native int SeqReader_FOLD_CASE_get();
  public final static native int SeqReader_NO_FOLD_CASE_get();
  public final static native int SeqReader_NO_TRIM_MASKED_get();
  public final static native int SeqReader_TRIM_MASKED_get();
  public final static native long new_SeqReader__SWIG_0(String jarg1, int jarg2);
  public final static native long new_SeqReader__SWIG_1(String jarg1);
  public final static native boolean SeqReader_flagFoldCase(long jarg1, SeqReader jarg1_);
  public final static native boolean SeqReader_flagTrimMasked(long jarg1, SeqReader jarg1_);
  public final static native int SeqReader_get_format(long jarg1, SeqReader jarg1_);
  public final static native int SeqReader_peek(long jarg1, SeqReader jarg1_);
  public final static native boolean SeqReader_read(long jarg1, SeqReader jarg1_);
  public final static native String SeqReader_seq(long jarg1, SeqReader jarg1_);
  public final static native String SeqReader_qual(long jarg1, SeqReader jarg1_);
  public final static native void SeqReader_manip(long jarg1, SeqReader jarg1_, long jarg2);
  public final static native void delete_SeqReader(long jarg1);
  public final static native void delete_Vertex(long jarg1);
  public final static native void delete_Edge(long jarg1);
  public final static native long new_Graph();
  public final static native long Graph_add_vertex(long jarg1, Graph jarg1_);
  public final static native void Graph_remove_vertex(long jarg1, Graph jarg1_, long jarg2, Vertex jarg2_);
  public final static native long Graph_add_edge(long jarg1, Graph jarg1_, long jarg2, Vertex jarg2_, long jarg3, Vertex jarg3_);
  public final static native void Graph_remove_edge(long jarg1, Graph jarg1_, long jarg2, Edge jarg2_);
  public final static native String Graph_to_string(long jarg1, Graph jarg1_);
  public final static native void delete_Graph(long jarg1);
  public final static native long split(String jarg1, String jarg2);
  public final static native void ltrim(long jarg1);
  public final static native void rtrim(long jarg1);
  public final static native void trim(long jarg1);
  public final static native boolean starts_with(String jarg1, String jarg2);
  public final static native boolean ends_with(String jarg1, String jarg2);
  public final static native void orig_open_set(long jarg1);
  public final static native long orig_open_get();
  public final static native void orig_open64_set(long jarg1);
  public final static native long orig_open64_get();
  public final static native void orig_creat_set(long jarg1);
  public final static native long orig_creat_get();
  public final static native void orig_fopen_set(long jarg1);
  public final static native long orig_fopen_get();
  public final static native void orig_fopen64_set(long jarg1);
  public final static native long orig_fopen64_get();
  public final static native void sigchld_handler(int jarg1);
  public final static native boolean data_saveload_init();
  public final static native boolean data_saveload_initialized_get();
  public final static native String get_saveload_cmd(String jarg1, boolean jarg2);
  public final static native int data_saveload(String jarg1, boolean jarg2);
  public final static native long fdata_saveload(String jarg1, boolean jarg2);
  public final static native int open(String jarg1, int jarg2, long jarg3);
  public final static native int open64(String jarg1, int jarg2, long jarg3);
  public final static native int creat(String jarg1, long jarg2);
  public final static native long fopen(String jarg1, String jarg2);
  public final static native long fopen64(String jarg1, String jarg2);
  public final static native String get_time();
  public final static native void log_info(String jarg1);
  public final static native void log_warning(String jarg1);
  public final static native void log_error(String jarg1);
  public final static native void check_error(boolean jarg1, String jarg2);
  public final static native void check_warning(boolean jarg1, String jarg2);
  public final static native void check_stream(long jarg1, String jarg2);
  public final static native String COMPLEMENTS_get();
  public final static native String CAPITALS_get();
}
