/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package btllib;

public final class SaveloadOp {
  public final static SaveloadOp READ = new SaveloadOp("READ");
  public final static SaveloadOp WRITE = new SaveloadOp("WRITE");
  public final static SaveloadOp APPEND = new SaveloadOp("APPEND");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SaveloadOp swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SaveloadOp.class + " with value " + swigValue);
  }

  private SaveloadOp(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SaveloadOp(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SaveloadOp(String swigName, SaveloadOp swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SaveloadOp[] swigValues = { READ, WRITE, APPEND };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

