/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Sequence {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Sequence(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Sequence obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        btlJNI.delete_Sequence(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Sequence() {
    this(btlJNI.new_Sequence__SWIG_0(), true);
  }

  public Sequence(Sequence seq) {
    this(btlJNI.new_Sequence__SWIG_1(Sequence.getCPtr(seq), seq), true);
  }

  public Sequence(String bases) {
    this(btlJNI.new_Sequence__SWIG_2(bases), true);
  }

  public Sequence(Sequence seq, long pos, long len) {
    this(btlJNI.new_Sequence__SWIG_3(Sequence.getCPtr(seq), seq, pos, len), true);
  }

  public Sequence(Sequence seq, long pos) {
    this(btlJNI.new_Sequence__SWIG_4(Sequence.getCPtr(seq), seq, pos), true);
  }

  public Sequence(String bases, long pos, long len) {
    this(btlJNI.new_Sequence__SWIG_5(bases, pos, len), true);
  }

  public Sequence(String bases, long pos) {
    this(btlJNI.new_Sequence__SWIG_6(bases, pos), true);
  }

  public Sequence(long n, char base) {
    this(btlJNI.new_Sequence__SWIG_7(n, base), true);
  }

  public SWIGTYPE_p_std__string__iterator begin() {
    return new SWIGTYPE_p_std__string__iterator(btlJNI.Sequence_begin(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__string__iterator end() {
    return new SWIGTYPE_p_std__string__iterator(btlJNI.Sequence_end(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__string__reverse_iterator rbegin() {
    return new SWIGTYPE_p_std__string__reverse_iterator(btlJNI.Sequence_rbegin(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__string__reverse_iterator rend() {
    return new SWIGTYPE_p_std__string__reverse_iterator(btlJNI.Sequence_rend(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__string__const_iterator cbegin() {
    return new SWIGTYPE_p_std__string__const_iterator(btlJNI.Sequence_cbegin(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__string__const_iterator cend() {
    return new SWIGTYPE_p_std__string__const_iterator(btlJNI.Sequence_cend(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__string__const_reverse_iterator crbegin() {
    return new SWIGTYPE_p_std__string__const_reverse_iterator(btlJNI.Sequence_crbegin(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__string__const_reverse_iterator crend() {
    return new SWIGTYPE_p_std__string__const_reverse_iterator(btlJNI.Sequence_crend(swigCPtr, this), true);
  }

  public long size() {
    return btlJNI.Sequence_size(swigCPtr, this);
  }

  public long length() {
    return btlJNI.Sequence_length(swigCPtr, this);
  }

  public long max_size() {
    return btlJNI.Sequence_max_size(swigCPtr, this);
  }

  public void resize(long n) {
    btlJNI.Sequence_resize__SWIG_0(swigCPtr, this, n);
  }

  public void resize(long n, char base) {
    btlJNI.Sequence_resize__SWIG_1(swigCPtr, this, n, base);
  }

  public long capacity() {
    return btlJNI.Sequence_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    btlJNI.Sequence_reserve__SWIG_0(swigCPtr, this, n);
  }

  public void reserve() {
    btlJNI.Sequence_reserve__SWIG_1(swigCPtr, this);
  }

  public void clear() {
    btlJNI.Sequence_clear(swigCPtr, this);
  }

  public boolean empty() {
    return btlJNI.Sequence_empty(swigCPtr, this);
  }

  public void shrink_to_fit() {
    btlJNI.Sequence_shrink_to_fit(swigCPtr, this);
  }

  public Base at(long pos) {
    return new Base(btlJNI.Sequence_at(swigCPtr, this, pos), true);
  }

  public Base back() {
    return new Base(btlJNI.Sequence_back(swigCPtr, this), true);
  }

  public Base front() {
    return new Base(btlJNI.Sequence_front(swigCPtr, this), true);
  }

  public Sequence add(Sequence rhs) {
    return new Sequence(btlJNI.Sequence_add__SWIG_0(swigCPtr, this, Sequence.getCPtr(rhs), rhs), false);
  }

  public Sequence add(String rhs) {
    return new Sequence(btlJNI.Sequence_add__SWIG_1(swigCPtr, this, rhs), false);
  }

  public Sequence add(char rhs) {
    return new Sequence(btlJNI.Sequence_add__SWIG_2(swigCPtr, this, rhs), false);
  }

  public Sequence append(Sequence seq) {
    return new Sequence(btlJNI.Sequence_append__SWIG_0(swigCPtr, this, Sequence.getCPtr(seq), seq), false);
  }

  public Sequence append(Sequence seq, long subpos, long sublen) {
    return new Sequence(btlJNI.Sequence_append__SWIG_1(swigCPtr, this, Sequence.getCPtr(seq), seq, subpos, sublen), false);
  }

  public Sequence append(String bases) {
    return new Sequence(btlJNI.Sequence_append__SWIG_2(swigCPtr, this, bases), false);
  }

  public Sequence append(String bases, long subpos, long sublen) {
    return new Sequence(btlJNI.Sequence_append__SWIG_3(swigCPtr, this, bases, subpos, sublen), false);
  }

  public Sequence append(String bases, long n) {
    return new Sequence(btlJNI.Sequence_append__SWIG_4(swigCPtr, this, bases, n), false);
  }

  public Sequence append(long n, char base) {
    return new Sequence(btlJNI.Sequence_append__SWIG_5(swigCPtr, this, n, base), false);
  }

  public void push_back(char base) {
    btlJNI.Sequence_push_back(swigCPtr, this, base);
  }

  public Sequence assign(Sequence seq) {
    return new Sequence(btlJNI.Sequence_assign__SWIG_0(swigCPtr, this, Sequence.getCPtr(seq), seq), false);
  }

  public Sequence assign(Sequence seq, long subpos, long sublen) {
    return new Sequence(btlJNI.Sequence_assign__SWIG_1(swigCPtr, this, Sequence.getCPtr(seq), seq, subpos, sublen), false);
  }

  public Sequence assign(Sequence seq, long subpos) {
    return new Sequence(btlJNI.Sequence_assign__SWIG_2(swigCPtr, this, Sequence.getCPtr(seq), seq, subpos), false);
  }

  public Sequence assign(String bases) {
    return new Sequence(btlJNI.Sequence_assign__SWIG_3(swigCPtr, this, bases), false);
  }

  public Sequence assign(String bases, long subpos, long sublen) {
    return new Sequence(btlJNI.Sequence_assign__SWIG_4(swigCPtr, this, bases, subpos, sublen), false);
  }

  public Sequence assign(String bases, long subpos) {
    return new Sequence(btlJNI.Sequence_assign__SWIG_5(swigCPtr, this, bases, subpos), false);
  }

  public Sequence assign(long n, char base) {
    return new Sequence(btlJNI.Sequence_assign__SWIG_6(swigCPtr, this, n, base), false);
  }

  public Sequence insert(long pos, Sequence seq) {
    return new Sequence(btlJNI.Sequence_insert__SWIG_0(swigCPtr, this, pos, Sequence.getCPtr(seq), seq), false);
  }

  public Sequence insert(long pos, Sequence seq, long subpos, long sublen) {
    return new Sequence(btlJNI.Sequence_insert__SWIG_1(swigCPtr, this, pos, Sequence.getCPtr(seq), seq, subpos, sublen), false);
  }

  public Sequence insert(long pos, Sequence seq, long subpos) {
    return new Sequence(btlJNI.Sequence_insert__SWIG_2(swigCPtr, this, pos, Sequence.getCPtr(seq), seq, subpos), false);
  }

  public Sequence insert(long pos, String bases) {
    return new Sequence(btlJNI.Sequence_insert__SWIG_3(swigCPtr, this, pos, bases), false);
  }

  public Sequence insert(long pos, String bases, long subpos, long sublen) {
    return new Sequence(btlJNI.Sequence_insert__SWIG_4(swigCPtr, this, pos, bases, subpos, sublen), false);
  }

  public Sequence insert(long pos, String bases, long subpos) {
    return new Sequence(btlJNI.Sequence_insert__SWIG_5(swigCPtr, this, pos, bases, subpos), false);
  }

  public Sequence insert(long pos, long n, char base) {
    return new Sequence(btlJNI.Sequence_insert__SWIG_6(swigCPtr, this, pos, n, base), false);
  }

  public SWIGTYPE_p_std__string__iterator insert(SWIGTYPE_p_std__string__const_iterator p, long n, char base) {
    return new SWIGTYPE_p_std__string__iterator(btlJNI.Sequence_insert__SWIG_7(swigCPtr, this, SWIGTYPE_p_std__string__const_iterator.getCPtr(p), n, base), true);
  }

  public SWIGTYPE_p_std__string__iterator insert(SWIGTYPE_p_std__string__const_iterator p, char base) {
    return new SWIGTYPE_p_std__string__iterator(btlJNI.Sequence_insert__SWIG_8(swigCPtr, this, SWIGTYPE_p_std__string__const_iterator.getCPtr(p), base), true);
  }

  public Sequence erase(long pos, long len) {
    return new Sequence(btlJNI.Sequence_erase__SWIG_0(swigCPtr, this, pos, len), false);
  }

  public Sequence erase(long pos) {
    return new Sequence(btlJNI.Sequence_erase__SWIG_1(swigCPtr, this, pos), false);
  }

  public Sequence erase() {
    return new Sequence(btlJNI.Sequence_erase__SWIG_2(swigCPtr, this), false);
  }

  public SWIGTYPE_p_std__string__iterator erase(SWIGTYPE_p_std__string__iterator p) {
    return new SWIGTYPE_p_std__string__iterator(btlJNI.Sequence_erase__SWIG_3(swigCPtr, this, SWIGTYPE_p_std__string__iterator.getCPtr(p)), true);
  }

  public SWIGTYPE_p_std__string__iterator erase(SWIGTYPE_p_std__string__iterator first, SWIGTYPE_p_std__string__iterator last) {
    return new SWIGTYPE_p_std__string__iterator(btlJNI.Sequence_erase__SWIG_4(swigCPtr, this, SWIGTYPE_p_std__string__iterator.getCPtr(first), SWIGTYPE_p_std__string__iterator.getCPtr(last)), true);
  }

  public Sequence replace(long pos, long len, Sequence seq) {
    return new Sequence(btlJNI.Sequence_replace__SWIG_0(swigCPtr, this, pos, len, Sequence.getCPtr(seq), seq), false);
  }

  public Sequence replace(long pos, long len, String bases) {
    return new Sequence(btlJNI.Sequence_replace__SWIG_1(swigCPtr, this, pos, len, bases), false);
  }

  public Sequence replace(SWIGTYPE_p_std__string__const_iterator i1, SWIGTYPE_p_std__string__const_iterator i2, Sequence seq) {
    return new Sequence(btlJNI.Sequence_replace__SWIG_2(swigCPtr, this, SWIGTYPE_p_std__string__const_iterator.getCPtr(i1), SWIGTYPE_p_std__string__const_iterator.getCPtr(i2), Sequence.getCPtr(seq), seq), false);
  }

  public Sequence replace(SWIGTYPE_p_std__string__const_iterator i1, SWIGTYPE_p_std__string__const_iterator i2, String bases) {
    return new Sequence(btlJNI.Sequence_replace__SWIG_3(swigCPtr, this, SWIGTYPE_p_std__string__const_iterator.getCPtr(i1), SWIGTYPE_p_std__string__const_iterator.getCPtr(i2), bases), false);
  }

  public Sequence replace(long pos, long len, Sequence seq, long subpos, long sublen) {
    return new Sequence(btlJNI.Sequence_replace__SWIG_4(swigCPtr, this, pos, len, Sequence.getCPtr(seq), seq, subpos, sublen), false);
  }

  public Sequence replace(long pos, long len, Sequence seq, long subpos) {
    return new Sequence(btlJNI.Sequence_replace__SWIG_5(swigCPtr, this, pos, len, Sequence.getCPtr(seq), seq, subpos), false);
  }

  public Sequence replace(long pos, long len, String bases, long subpos, long sublen) {
    return new Sequence(btlJNI.Sequence_replace__SWIG_6(swigCPtr, this, pos, len, bases, subpos, sublen), false);
  }

  public Sequence replace(long pos, long len, String bases, long subpos) {
    return new Sequence(btlJNI.Sequence_replace__SWIG_7(swigCPtr, this, pos, len, bases, subpos), false);
  }

  public Sequence replace(SWIGTYPE_p_std__string__const_iterator i1, SWIGTYPE_p_std__string__const_iterator i2, String bases, long n) {
    return new Sequence(btlJNI.Sequence_replace__SWIG_8(swigCPtr, this, SWIGTYPE_p_std__string__const_iterator.getCPtr(i1), SWIGTYPE_p_std__string__const_iterator.getCPtr(i2), bases, n), false);
  }

  public Sequence replace(long pos, long len, long n, char base) {
    return new Sequence(btlJNI.Sequence_replace__SWIG_9(swigCPtr, this, pos, len, n, base), false);
  }

  public Sequence replace(SWIGTYPE_p_std__string__const_iterator i1, SWIGTYPE_p_std__string__const_iterator i2, long n, char base) {
    return new Sequence(btlJNI.Sequence_replace__SWIG_10(swigCPtr, this, SWIGTYPE_p_std__string__const_iterator.getCPtr(i1), SWIGTYPE_p_std__string__const_iterator.getCPtr(i2), n, base), false);
  }

  public void swap(Sequence seq) {
    btlJNI.Sequence_swap__SWIG_0(swigCPtr, this, Sequence.getCPtr(seq), seq);
  }

  public void swap(SWIGTYPE_p_std__string bases) {
    btlJNI.Sequence_swap__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(bases));
  }

  public void pop_back() {
    btlJNI.Sequence_pop_back(swigCPtr, this);
  }

  public String c_str() {
    return btlJNI.Sequence_c_str(swigCPtr, this);
  }

  public String data() {
    return btlJNI.Sequence_data(swigCPtr, this);
  }

  public SWIGTYPE_p_std__string__allocator_type get_allocator() {
    return new SWIGTYPE_p_std__string__allocator_type(btlJNI.Sequence_get_allocator(swigCPtr, this), true);
  }

  public long copy(String bases, long len, long pos) {
    return btlJNI.Sequence_copy__SWIG_0(swigCPtr, this, bases, len, pos);
  }

  public long copy(String bases, long len) {
    return btlJNI.Sequence_copy__SWIG_1(swigCPtr, this, bases, len);
  }

  public long find(Sequence seq, long pos) {
    return btlJNI.Sequence_find__SWIG_0(swigCPtr, this, Sequence.getCPtr(seq), seq, pos);
  }

  public long find(Sequence seq) {
    return btlJNI.Sequence_find__SWIG_1(swigCPtr, this, Sequence.getCPtr(seq), seq);
  }

  public long find(String bases, long pos) {
    return btlJNI.Sequence_find__SWIG_2(swigCPtr, this, bases, pos);
  }

  public long find(String bases) {
    return btlJNI.Sequence_find__SWIG_3(swigCPtr, this, bases);
  }

  public long find(String bases, long pos, SWIGTYPE_p_std__string__size_type n) {
    return btlJNI.Sequence_find__SWIG_4(swigCPtr, this, bases, pos, SWIGTYPE_p_std__string__size_type.getCPtr(n));
  }

  public long find(char base, long pos) {
    return btlJNI.Sequence_find__SWIG_5(swigCPtr, this, base, pos);
  }

  public long find(char base) {
    return btlJNI.Sequence_find__SWIG_6(swigCPtr, this, base);
  }

  public long rfind(Sequence seq, long pos) {
    return btlJNI.Sequence_rfind__SWIG_0(swigCPtr, this, Sequence.getCPtr(seq), seq, pos);
  }

  public long rfind(Sequence seq) {
    return btlJNI.Sequence_rfind__SWIG_1(swigCPtr, this, Sequence.getCPtr(seq), seq);
  }

  public long rfind(String bases, long pos) {
    return btlJNI.Sequence_rfind__SWIG_2(swigCPtr, this, bases, pos);
  }

  public long rfind(String bases) {
    return btlJNI.Sequence_rfind__SWIG_3(swigCPtr, this, bases);
  }

  public long rfind(String bases, long pos, long n) {
    return btlJNI.Sequence_rfind__SWIG_4(swigCPtr, this, bases, pos, n);
  }

  public long rfind(char base, long pos) {
    return btlJNI.Sequence_rfind__SWIG_5(swigCPtr, this, base, pos);
  }

  public long rfind(char base) {
    return btlJNI.Sequence_rfind__SWIG_6(swigCPtr, this, base);
  }

  public long find_first_of(Sequence seq, long pos) {
    return btlJNI.Sequence_find_first_of__SWIG_0(swigCPtr, this, Sequence.getCPtr(seq), seq, pos);
  }

  public long find_first_of(Sequence seq) {
    return btlJNI.Sequence_find_first_of__SWIG_1(swigCPtr, this, Sequence.getCPtr(seq), seq);
  }

  public long find_first_of(String bases, long pos) {
    return btlJNI.Sequence_find_first_of__SWIG_2(swigCPtr, this, bases, pos);
  }

  public long find_first_of(String bases) {
    return btlJNI.Sequence_find_first_of__SWIG_3(swigCPtr, this, bases);
  }

  public long find_first_of(String bases, long pos, long n) {
    return btlJNI.Sequence_find_first_of__SWIG_4(swigCPtr, this, bases, pos, n);
  }

  public long find_first_of(char base, long pos) {
    return btlJNI.Sequence_find_first_of__SWIG_5(swigCPtr, this, base, pos);
  }

  public long find_first_of(char base) {
    return btlJNI.Sequence_find_first_of__SWIG_6(swigCPtr, this, base);
  }

  public long find_last_of(Sequence seq, long pos) {
    return btlJNI.Sequence_find_last_of__SWIG_0(swigCPtr, this, Sequence.getCPtr(seq), seq, pos);
  }

  public long find_last_of(Sequence seq) {
    return btlJNI.Sequence_find_last_of__SWIG_1(swigCPtr, this, Sequence.getCPtr(seq), seq);
  }

  public long find_last_of(String bases, long pos) {
    return btlJNI.Sequence_find_last_of__SWIG_2(swigCPtr, this, bases, pos);
  }

  public long find_last_of(String bases) {
    return btlJNI.Sequence_find_last_of__SWIG_3(swigCPtr, this, bases);
  }

  public long find_last_of(String bases, long pos, long n) {
    return btlJNI.Sequence_find_last_of__SWIG_4(swigCPtr, this, bases, pos, n);
  }

  public long find_last_of(char base, long pos) {
    return btlJNI.Sequence_find_last_of__SWIG_5(swigCPtr, this, base, pos);
  }

  public long find_last_of(char base) {
    return btlJNI.Sequence_find_last_of__SWIG_6(swigCPtr, this, base);
  }

  public long find_first_not_of(Sequence seq, long pos) {
    return btlJNI.Sequence_find_first_not_of__SWIG_0(swigCPtr, this, Sequence.getCPtr(seq), seq, pos);
  }

  public long find_first_not_of(Sequence seq) {
    return btlJNI.Sequence_find_first_not_of__SWIG_1(swigCPtr, this, Sequence.getCPtr(seq), seq);
  }

  public long find_first_not_of(String bases, long pos) {
    return btlJNI.Sequence_find_first_not_of__SWIG_2(swigCPtr, this, bases, pos);
  }

  public long find_first_not_of(String bases) {
    return btlJNI.Sequence_find_first_not_of__SWIG_3(swigCPtr, this, bases);
  }

  public long find_first_not_of(String bases, long pos, long n) {
    return btlJNI.Sequence_find_first_not_of__SWIG_4(swigCPtr, this, bases, pos, n);
  }

  public long find_first_not_of(char base, long pos) {
    return btlJNI.Sequence_find_first_not_of__SWIG_5(swigCPtr, this, base, pos);
  }

  public long find_first_not_of(char base) {
    return btlJNI.Sequence_find_first_not_of__SWIG_6(swigCPtr, this, base);
  }

  public long find_last_not_of(Sequence seq, long pos) {
    return btlJNI.Sequence_find_last_not_of__SWIG_0(swigCPtr, this, Sequence.getCPtr(seq), seq, pos);
  }

  public long find_last_not_of(Sequence seq) {
    return btlJNI.Sequence_find_last_not_of__SWIG_1(swigCPtr, this, Sequence.getCPtr(seq), seq);
  }

  public long find_last_not_of(String bases, long pos) {
    return btlJNI.Sequence_find_last_not_of__SWIG_2(swigCPtr, this, bases, pos);
  }

  public long find_last_not_of(String bases) {
    return btlJNI.Sequence_find_last_not_of__SWIG_3(swigCPtr, this, bases);
  }

  public long find_last_not_of(String bases, long pos, long n) {
    return btlJNI.Sequence_find_last_not_of__SWIG_4(swigCPtr, this, bases, pos, n);
  }

  public long find_last_not_of(char base, long pos) {
    return btlJNI.Sequence_find_last_not_of__SWIG_5(swigCPtr, this, base, pos);
  }

  public long find_last_not_of(char base) {
    return btlJNI.Sequence_find_last_not_of__SWIG_6(swigCPtr, this, base);
  }

  public Sequence substr(long pos, long len) {
    return new Sequence(btlJNI.Sequence_substr__SWIG_0(swigCPtr, this, pos, len), true);
  }

  public Sequence substr(long pos) {
    return new Sequence(btlJNI.Sequence_substr__SWIG_1(swigCPtr, this, pos), true);
  }

  public Sequence substr() {
    return new Sequence(btlJNI.Sequence_substr__SWIG_2(swigCPtr, this), true);
  }

  public int compare(Sequence seq) {
    return btlJNI.Sequence_compare__SWIG_0(swigCPtr, this, Sequence.getCPtr(seq), seq);
  }

  public int compare(String bases) {
    return btlJNI.Sequence_compare__SWIG_1(swigCPtr, this, bases);
  }

  public int compare(long pos, long len, Sequence seq) {
    return btlJNI.Sequence_compare__SWIG_2(swigCPtr, this, pos, len, Sequence.getCPtr(seq), seq);
  }

  public int compare(long pos, long len, String bases) {
    return btlJNI.Sequence_compare__SWIG_3(swigCPtr, this, pos, len, bases);
  }

  public int compare(long pos, long len, Sequence seq, long subpos, long sublen) {
    return btlJNI.Sequence_compare__SWIG_4(swigCPtr, this, pos, len, Sequence.getCPtr(seq), seq, subpos, sublen);
  }

  public int compare(long pos, long len, Sequence seq, long subpos) {
    return btlJNI.Sequence_compare__SWIG_5(swigCPtr, this, pos, len, Sequence.getCPtr(seq), seq, subpos);
  }

  public int compare(long pos, long len, String bases, long subpos, long sublen) {
    return btlJNI.Sequence_compare__SWIG_6(swigCPtr, this, pos, len, bases, subpos, sublen);
  }

  public int compare(long pos, long len, String bases, long subpos) {
    return btlJNI.Sequence_compare__SWIG_7(swigCPtr, this, pos, len, bases, subpos);
  }

  public void reverseComplement() {
    btlJNI.Sequence_reverseComplement(swigCPtr, this);
  }

  public Sequence getReverseComplement() {
    return new Sequence(btlJNI.Sequence_getReverseComplement(swigCPtr, this), true);
  }

  public final static long npos = btlJNI.Sequence_npos_get();
}
