#!/bin/bash

if [ -z "${MESON_SOURCE_ROOT}" ]; then
  echo "[ERROR] This script can only be ran with meson!"
  exit 1
fi

set -e

cd "${MESON_SOURCE_ROOT}"

files=$(scripts/get-files include)
files+=$(scripts/get-files tests)
files+=$(scripts/get-files examples)
files+=$(scripts/get-files recipes)
for file in $files; do
  diff $file <(clang-format -style=mozilla $file)
done