#!/bin/bash

if [ -z "${MESON_SOURCE_ROOT}" ]; then
  echo "[ERROR] This script can only be ran with meson!"
  exit 1
fi

get_lib_paths() {
  local lib_paths=()
  for flag in $1; do
    if [[ $flag == "-L"* ]]; then
      lib_paths+=($flag)
    fi
  done
  echo "${lib_paths[@]}"
}

cd "${MESON_SOURCE_ROOT}"

if [[ -n "$BTLLIB_PYTHON_CFLAGS" ]]; then
  cflags="$BTLLIB_PYTHON_CFLAGS"
  ldflags="$BTLLIB_PYTHON_LDFLAGS"
else
  cflags=$(python3-config --cflags)
  ldflags=$(python3-config --ldflags)
fi

found_libpython=0
for flag in $ldflags; do
  if [[ $flag == "-lpython"* ]]; then
    found_libpython=1
  fi
done

if [[ $found_libpython -eq 0 ]]; then
  if [[ -n "$BTLLIB_PYTHON_VERSION" ]]; then
    py_version_major_minor="$BTLLIB_PYTHON_VERSION"
  else
    py_version_major_minor=$(python3 --version | awk '{print $2}' | awk -F '.' '{print $1 "." $2}')
  fi
  py_version_major=$(echo $py_version_major_minor | awk -F '.' '{print $1}')

  pylibs=( "python${py_version_major_minor}" "python${py_version_major_minor}m" "python${py_version_major}" "python" )
  libdetects=( "" "" "" "" )

  lib_paths="$(get_lib_paths "${ldflags}")"

  found=0
  for i in $(seq 0 3); do
    l=${pylibs[$i]}
    for lp in $lib_paths; do
      p=${lp:2}
      libsfound="$(find "$p" -maxdepth 1 -regextype sed -regex ".*lib${l}\.\(so\|dylib\|tbd\|a\)")"
      if [[ -n "$libsfound" ]]; then
        ldflags+=" -l${l}"
        found=1
        break
      fi
    done
    if [[ $found -eq 1 ]]; then
      break
    fi
  done
  if [[ $found -eq 0 ]]; then
    echo "ERROR"
    echo "Python library (.so, .dylib, .tbd, or .a) not found!"
    exit 1
  fi
fi

echo "SUCCESS"
echo "$cflags"
echo "$ldflags"