name: Paper

on: push

jobs:
  build_paper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Open Journals PDF Generator
        uses: openjournals/openjournals-draft-action@v.1.0